// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.1
// 	protoc        v3.11.4
// source: types/os/os.proto

package os

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type OS_Type int32

const (
	OS_Type_unknown       OS_Type = 0
	OS_Type_Windows_Phone OS_Type = 1
	OS_Type_Windows       OS_Type = 2
	OS_Type_Mac_OSX       OS_Type = 3
	OS_Type_iOS           OS_Type = 4
	OS_Type_Android       OS_Type = 5
	OS_Type_Blackberry    OS_Type = 6
	OS_Type_Chrome_OS     OS_Type = 7
	OS_Type_Kindle        OS_Type = 8
	OS_Type_Web_OS        OS_Type = 9
	OS_Type_Linux         OS_Type = 10
	OS_Type_Playstation   OS_Type = 11
	OS_Type_Xbox          OS_Type = 12
	OS_Type_Nintendo      OS_Type = 13
	OS_Type_Bot           OS_Type = 14
)

// Enum value maps for OS_Type.
var (
	OS_Type_name = map[int32]string{
		0:  "unknown",
		1:  "Windows_Phone",
		2:  "Windows",
		3:  "Mac_OSX",
		4:  "iOS",
		5:  "Android",
		6:  "Blackberry",
		7:  "Chrome_OS",
		8:  "Kindle",
		9:  "Web_OS",
		10: "Linux",
		11: "Playstation",
		12: "Xbox",
		13: "Nintendo",
		14: "Bot",
	}
	OS_Type_value = map[string]int32{
		"unknown":       0,
		"Windows_Phone": 1,
		"Windows":       2,
		"Mac_OSX":       3,
		"iOS":           4,
		"Android":       5,
		"Blackberry":    6,
		"Chrome_OS":     7,
		"Kindle":        8,
		"Web_OS":        9,
		"Linux":         10,
		"Playstation":   11,
		"Xbox":          12,
		"Nintendo":      13,
		"Bot":           14,
	}
)

func (x OS_Type) Enum() *OS_Type {
	p := new(OS_Type)
	*p = x
	return p
}

func (x OS_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OS_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_types_os_os_proto_enumTypes[0].Descriptor()
}

func (OS_Type) Type() protoreflect.EnumType {
	return &file_types_os_os_proto_enumTypes[0]
}

func (x OS_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OS_Type.Descriptor instead.
func (OS_Type) EnumDescriptor() ([]byte, []int) {
	return file_types_os_os_proto_rawDescGZIP(), []int{0}
}

var File_types_os_os_proto protoreflect.FileDescriptor

var file_types_os_os_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x6f, 0x73, 0x2f, 0x6f, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x11, 0x75, 0x61, 0x73, 0x75, 0x72, 0x66, 0x65, 0x72, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x6f, 0x73, 0x2a, 0xcd, 0x01, 0x0a, 0x07, 0x4f, 0x53, 0x5f, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12,
	0x11, 0x0a, 0x0d, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73, 0x5f, 0x50, 0x68, 0x6f, 0x6e, 0x65,
	0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73, 0x10, 0x02, 0x12,
	0x0b, 0x0a, 0x07, 0x4d, 0x61, 0x63, 0x5f, 0x4f, 0x53, 0x58, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03,
	0x69, 0x4f, 0x53, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64,
	0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x62, 0x65, 0x72, 0x72, 0x79,
	0x10, 0x06, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x68, 0x72, 0x6f, 0x6d, 0x65, 0x5f, 0x4f, 0x53, 0x10,
	0x07, 0x12, 0x0a, 0x0a, 0x06, 0x4b, 0x69, 0x6e, 0x64, 0x6c, 0x65, 0x10, 0x08, 0x12, 0x0a, 0x0a,
	0x06, 0x57, 0x65, 0x62, 0x5f, 0x4f, 0x53, 0x10, 0x09, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x69, 0x6e,
	0x75, 0x78, 0x10, 0x0a, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x79, 0x73, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x10, 0x0b, 0x12, 0x08, 0x0a, 0x04, 0x58, 0x62, 0x6f, 0x78, 0x10, 0x0c, 0x12,
	0x0c, 0x0a, 0x08, 0x4e, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x6f, 0x10, 0x0d, 0x12, 0x07, 0x0a,
	0x03, 0x42, 0x6f, 0x74, 0x10, 0x0e, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x69, 0x67, 0x65, 0x6c, 0x74, 0x69, 0x61, 0x6e, 0x79, 0x2f,
	0x75, 0x61, 0x73, 0x75, 0x72, 0x66, 0x65, 0x72, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x6f,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_types_os_os_proto_rawDescOnce sync.Once
	file_types_os_os_proto_rawDescData = file_types_os_os_proto_rawDesc
)

func file_types_os_os_proto_rawDescGZIP() []byte {
	file_types_os_os_proto_rawDescOnce.Do(func() {
		file_types_os_os_proto_rawDescData = protoimpl.X.CompressGZIP(file_types_os_os_proto_rawDescData)
	})
	return file_types_os_os_proto_rawDescData
}

var file_types_os_os_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_types_os_os_proto_goTypes = []interface{}{
	(OS_Type)(0), // 0: uasurfer.types.os.OS_Type
}
var file_types_os_os_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_types_os_os_proto_init() }
func file_types_os_os_proto_init() {
	if File_types_os_os_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_types_os_os_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_os_os_proto_goTypes,
		DependencyIndexes: file_types_os_os_proto_depIdxs,
		EnumInfos:         file_types_os_os_proto_enumTypes,
	}.Build()
	File_types_os_os_proto = out.File
	file_types_os_os_proto_rawDesc = nil
	file_types_os_os_proto_goTypes = nil
	file_types_os_os_proto_depIdxs = nil
}
